-- TẠO CƠ SỞ DỮ LIỆU  QUẢN LÝ BỆNH VIỆN 
CREATE DATABASE QLBV 
GO

-- DÙNG CƠ SỞ DỮ LIỆU QUẢN LÝ BỆNH VIỆN 
USE QLBV 
GO 

-- XOÁ CƠ SỞ DỮ LIỆU QUẢN LÝ BỆNH VIỆN 
--DROP DATABASE QLBV 

-- TAỌ BẢNG 

-- TẠO BẢNG KHOA 
CREATE TABLE KHOA (MAK CHAR(20) NOT NULL , TENK NVARCHAR (30) )
GO 
--TẠO BẢNG NHANVIEN
CREATE TABLE NHANVIEN (MANV CHAR (20)NOT NULL ,HONV NVARCHAR(30), TENNV NVARCHAR (30) , SODTH VARCHAR(11), 
DIACHI NVARCHAR(50), NGAYSINH DATETIME , PHAI NVARCHAR(10), CHUCVU NVARCHAR (20) , NGAYLV DATETIME )
GO 
-- TẠO BẢNG BÁC SĨ 
CREATE TABLE BACSI (MABS CHAR (20)NOT NULL ,HOBS NVARCHAR(30), TENBS NVARCHAR (30) ,  CHUCVU NVARCHAR (20) , MaK CHAR (20))
GO 
-- TẠO BẢNG BỆNH NHÂN 
CREATE TABLE BENHNHAN (MABN CHAR (20)NOT NULL,HOBN NVARCHAR(30) , TENBN NVARCHAR (30) , SODTH VARCHAR(11), 
DIACHI NVARCHAR(50), NGAYSINH DATETIME , PHAI NVARCHAR(10),MAPHG CHAR (20) )
GO 
-- TẠO BẢNG THUỐC 
CREATE TABLE THUOC (MATHUOC CHAR (13) NOT NULL  , TENTHUOC NVARCHAR (100), SL TINYINT , GIA MONEY )
GO 
-- TẠO BẢNG HÓA ĐƠN
CREATE TABLE HOADON (MAHD CHAR (20) NOT NULL , MADV CHAR (20) , SL TINYINT , THANHTIEN MONEY , THUOC CHAR (13), MABN CHAR (20) NOT NULL )
GO 
-- TẠO BẢNG Dịch vụ 
CREATE TABLE DICHVU (MADV CHAR (20) NOT NULL , TENDV NVARCHAR (100) ,GIA MONEY )
GO 
-- TẠO BẢNG BỆNH ÁN 
CREATE TABLE BENHAN (MABA CHAR (20) NOT NULL ,MABN CHAR (20), KETQUA NVARCHAR (50))
GO 
--TẠO BẢNG PHÒNG ĐIỀU TRỊ 
CREATE TABLE PHONGDIEUTRI (MAPDT CHAR(20 )NOT NULL , LOAIPHONG NVARCHAR (30))
GO
-- TẠO BẢNG PHÒNG KHÁM 
CREATE TABLE PHONGKHAM(MAPK CHAR (20 )NOT NULL , MAK CHAR (20) NOT NULL )
GO
-- TẠO BẢNG BHYT 
CREATE TABLE BHYT (MABHYT CHAR (15)NOT NULL ,MABN CHAR (20) unique NOT NULL, NGAYCAP DATE , NGAYHETHAN DATE )
GO


-- TẠO BẢNG CHO CÁC MỐI LIÊN KẾT 
-- TẠO BẢNG ĐIỀU TRỊ 
CREATE TABLE DIEUTRI (MAK CHAR(20) NOT NULL,MABN CHAR (20)NOT NULL)
GO 
-- TẠO BẢNG KHOA_NV 
CREATE TABLE KHOA_NV (MAK CHAR(20) NOT NULL,MANV CHAR (20)NOT NULL)
GO 
--TẠO BẢNG LICHSU_BA
CREATE TABLE LICHSU_BA (MABS CHAR(20) NOT NULL,MABA CHAR (20)NOT NULL, NGAYVIET DATE )
GO 
-- TẠO BẢNG KHAM_BENH
CREATE TABLE KHAM_BENH (MABS CHAR(20) NOT NULL,MABN CHAR (20)NOT NULL, NGAYKHAM DATE )
GO 
-- TẠO BẢNG MUA_THUOC
CREATE TABLE MUA_THUOC (MATHUOC CHAR(13) NOT NULL,MABN CHAR (20)NOT NULL , SL INT)
GO 
-- TẠO BẢNG SUDUNG_DICHVU
CREATE TABLE SUDUNG_DICHVU(MADV CHAR(20) NOT NULL,MABN CHAR (20)NOT NULL , TGIAN DATE, SL INT)
GO 
-- TẠO BẢNG PHÒNG KHÁM_BỆNH NHÂN 
CREATE TABLE PKHAM_BENHNHAN (MAPK CHAR(20) NOT NULL , MABN CHAR (20) NOT NULL, TGIAN DATE)
GO
-- XOA BẢNG 
--DROP TABLE KHOA 
--DROP TABLE NHANVIEN
--DROP TABLE BACSI
--DROP TABLE BENHNHAN
--DROP TABLE THUOC
--DROP TABLE HOADON
--DROP TABLE DICHVU
--DROP TABLE BENHAN
--DROP TABLE PHONGDIEUTRI
--DROP TABLE BHYT 
--DROP TABLE PHONGKHAM

-- XÓA BẢNG MỐI LIÊN KẾT 
--DROP TABLE DIEUTRI
--DROP TABLE KHOA_NV 
--DROP TABLE LICHSU_BA
--DROP TABLE KHAM_BENH 
--DROP TABLE MUA_THUOC
--DROP TABLE SUDUNG_DICHVU

-- THÊM KHÓA CHÍNH CHO BẢNG 
-- KHÓA CHÍNH CỦA KHOA 
 ALTER TABLE KHOA 
 ADD CONSTRAINT PK_K PRIMARY KEY (MAK)
 GO 
 -- KHÓA CHÍNH CỦA NHÂN VIÊN 
 ALTER TABLE NHANVIEN
 ADD CONSTRAINT PK_NV PRIMARY KEY (MANV)
 GO 
  -- KHÓA CHÍNH CỦA BÁC SĨ 
 ALTER TABLE BACSI
 ADD CONSTRAINT PK_BS PRIMARY KEY (MABS)
 GO 
  -- KHÓA CHÍNH CỦA BỆNH NHÂN 
 ALTER TABLE BENHNHAN
 ADD CONSTRAINT PK_BN PRIMARY KEY (MABN)
 GO 
  -- KHÓA CHÍNH CỦA BỆNH ÁN 
 ALTER TABLE BENHAN
 ADD CONSTRAINT PK_BA PRIMARY KEY (MABA)
 GO 
  -- KHÓA CHÍNH CỦA HÓA ĐƠN 
 ALTER TABLE HOADON
 ADD CONSTRAINT PK_HD PRIMARY KEY (MAHD)
 GO 
  -- KHÓA CHÍNH CỦA DỊCH VỤ 
 ALTER TABLE DICHVU 
 ADD CONSTRAINT PK_DV PRIMARY KEY (MADV)
 GO 
  -- KHÓA CHÍNH CỦA THUỐC 
 ALTER TABLE THUOC 
 ADD CONSTRAINT PK_T PRIMARY KEY (MATHUOC)
 GO 
  -- KHÓA CHÍNH CỦA PHÒNG 
 ALTER TABLE PHONGDIEUTRI
 ADD CONSTRAINT PK_PDT PRIMARY KEY (MAPDT)
 GO 
  -- KHÓA CHÍNH CỦA BHYT 
  ALTER TABLE BHYT 
  ADD CONSTRAINT PK_BHYT PRIMARY KEY (MABHYT)
  GO
  -- KHOÁ CHÍNH CỦA PHÒNG KHÁM 
  ALTER TABLE PHONGKHAM 
  ADD CONSTRAINT PK_PK PRIMARY KEY (MAPK)
  GO
 -- TẠO KHÓA CHÍNH CHO CÁI MỐI KẾT HỢP 
  -- KHÓA CHÍNH CỦA ĐIỀU TRỊ 
  ALTER TABLE DIEUTRI 
  ADD CONSTRAINT PK_DT PRIMARY KEY (MAK , MABN)
  GO
  -- KHÓA CHÍNH CỦA KHÁM BỆNH 
 ALTER TABLE KHAM_BENH
 ADD CONSTRAINT PK_KB PRIMARY KEY (MABN,MaBS)
 GO 
  -- KHÓA CHÍNH CỦA KHOA NHÂN VIÊN 
 ALTER TABLE KHOA_NV
 ADD CONSTRAINT PK_KNV PRIMARY KEY (MAK,MANV)
 GO 
  -- KHÓA CHÍNH CỦA LỊCH SỬ BỆNH ÁN 
 ALTER TABLE LICHSU_BA
 ADD CONSTRAINT PK_LSBA PRIMARY KEY (MABS,MABA)
 GO 
  -- KHÓA CHÍNH CỦA MUA THUỐC 
 ALTER TABLE MUA_THUOC
 ADD CONSTRAINT PK_MT PRIMARY KEY (MABN, MATHUOC)
 GO 
  -- KHÓA CHÍNH CỦA SỬ DỤNG DỊCH VỤ 
 ALTER TABLE SUDUNG_DICHVU
 ADD CONSTRAINT PK_SD_DV PRIMARY KEY (MABN, MADV)
 GO 
 -- KHOÁ CHÍNH CHO PHÒNG KHÁM _ BỆNH NHÂN 
 ALTER TABLE PKHAM_BENHNHAN 
 ADD CONSTRAINT PK_PK_BN PRIMARY KEY (MAPK , MABN)
 GO

 

 -- KHÓA NGOẠI CHO CAC BẢNG 

 -----KHÓA NGOẠI CỦA BÁC SĨ-------------------
 ALTER TABLE BACSI 
 ADD CONSTRAINT FK_BS_K FOREIGN KEY (MAK) REFERENCES KHOA (MAK)
 GO
 -----KHÓA NGOẠI CỦA KHOA_NHANVIEN -------------
 ALTER TABLE KHOA_NV
ADD CONSTRAINT FK_KNV_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV) 
GO

 ALTER TABLE KHOA_NV
ADD CONSTRAINT FK_KNV_K FOREIGN KEY (MAK) REFERENCES KHOA(MAK) 
GO
--- KHÓA NGOẠI CỦA BỆNH ÁN 
ALTER TABLE BENHAN 
ADD CONSTRAINT FK_BA_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
GO
 -----KHÓA NGOẠI CỦA LICHSU_BENHAN -------------
 ALTER TABLE LICHSU_BA
ADD CONSTRAINT FK_LSBA_BS FOREIGN KEY (MABS) REFERENCES BACSI (MABS) 
GO

ALTER TABLE LICHSU_BA
ADD CONSTRAINT FK_LSBA_BA FOREIGN KEY (MABA) REFERENCES BENHAN (MABA) 
GO
-----KHÓA NGOẠI CỦA BENHNHAN -------------
ALTER TABLE BENHNHAN
ADD CONSTRAINT FK_BN_PHG FOREIGN KEY (MAPHG) REFERENCES PHONGDIEUTRI (MAPDT) 
GO

-----KHÓA NGOẠI CỦA KHAMBENN -------------
 ALTER TABLE KHAM_BENH
ADD CONSTRAINT FK_KB_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN (MABN)
GO

 ALTER TABLE KHAM_BENH
ADD CONSTRAINT FK_KB_BS FOREIGN KEY (MABS) REFERENCES BACSI (MABS)
GO

-----KHÓA NGOẠI CỦA HOADON -------------
 ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN (MABN)
GO
 -----KHÓA NGOẠI CỦA DICHVU -------------
 ALTER TABLE SUDUNG_DICHVU
ADD CONSTRAINT FK_SDDV_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN (MABN)
GO

 ALTER TABLE SUDUNG_DICHVU
ADD CONSTRAINT FK_SDDV_DV FOREIGN KEY (MADV) REFERENCES DICHVU (MADV)
GO

-----KHÓA NGOẠI CỦA MUA_THUOC -------------
 ALTER TABLE MUA_THUOC
ADD CONSTRAINT FK_MT_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN (MABN)
GO

 ALTER TABLE MUA_THUOC
ADD CONSTRAINT FK_MT_T FOREIGN KEY (MATHUOC) REFERENCES THUOC (MATHUOC)
GO


-----KHÓA NGOẠI CỦA DIEUTRI -------------
 ALTER TABLE DIEUTRI
ADD CONSTRAINT FK_DT_K FOREIGN KEY (MAK) REFERENCES KHOA (MAK)
GO

 ALTER TABLE DIEUTRI
ADD CONSTRAINT FK_DT_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN (MABN)
GO

----------------BHYT-------------------------
 ALTER TABLE BHYT
ADD CONSTRAINT FK_BHYT_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN (MABN)
GO

----------------KHOÁ NGOẠI CHO PHÒNG KHÁM _ BỆNH NHÂN -------------------------
ALTER TABLE PKHAM_BENHNHAN
ADD CONSTRAINT FK_PKBN_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
GO
 
 ALTER TABLE PKHAM_BENHNHAN 
 ADD CONSTRAINT FK_PKBN_PK FOREIGN KEY (MAPK) REFERENCES PHONGKHAM (MAPK)
 GO 
----------------KHOÁ NGOẠI CHO PHÒNG KHÁM  -------------------------
ALTER TABLE PHONGKHAM 
ADD CONSTRAINT FK_PK_K FOREIGN KEY (MAK) REFERENCES KHOA(MAK)
GO
-- RÀNG BUỘC DUY NHẤT
ALTER TABLE KHOA 
ADD CONSTRAINT UN_TENK UNIQUE (TENK)
GO

ALTER TABLE THUOC 
ADD CONSTRAINT UN_TENT UNIQUE (TENTHUOC)
GO
-- RÀNG BUỘC MIỀN GIÁ TRỊ 
ALTER TABLE NHANVIEN 
ADD CONSTRAINT CK_PHAI CHECK (PHAI=N'NAM' OR PHAI = N'NỮ')
GO

ALTER TABLE NHANVIEN 
ADD CONSTRAINT CK_TUOI CHECK (NGAYSINH >=18 )
GO

ALTER TABLE BENHNHAN
ADD CONSTRAINT CK_PBN CHECK (PHAI=N'NAM' OR PHAI = N'NỮ')
GO

ALTER TABLE MUA_THUOC
ADD CONSTRAINT CK_SL CHECK (SL>=1)
GO 

ALTER TABLE THUOC 
ADD CONSTRAINT CK_GIA CHECK (GIA>=0)
GO 

ALTER TABLE HOADON 
ADD CONSTRAINT CK_TT CHECK (THANHTIEN >=0)
GO

-- RÀNG BUỘC MẠC ĐỊNH 
ALTER TABLE THUOC 
ADD CONSTRAINT DF_GIA DEFAULT 0.0 FOR GIA 
GO 

ALTER TABLE HOADON 
ADD CONSTRAINT DF_TT DEFAULT 0.0 FOR THANHTIEN 
GO